# Generated by Django 5.0.4 on 2024-05-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_manzana'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_proyecto',
            name='id_personalizado',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sub_proyecto',
            name='manzana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.manzana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub_proyecto',
            name='estado',
            field=models.CharField(choices=[('VENDIDO', 'Vendido'), ('CUOTAS', 'Cuotas'), ('DISPONIBLE', 'Disponible'), ('SEPARADO', 'Separado')], default='DISPONIBLE', max_length=20, verbose_name='Estado'),
        ),
    ]
