# Generated by Django 5.0.4 on 2024-05-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='proyecto',
            field=models.CharField(default=2, max_length=500, verbose_name='Proyecto'),
            preserve_default=False,
        ),
    ]
