# Generated by Django 5.0.4 on 2024-05-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotas',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('no_pagado', 'No pagado'), ('cancelado', 'Cancelado')], default='no_pagado', max_length=20),
        ),
    ]
