# Generated by Django 5.0.4 on 2024-05-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cuotas_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotas',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='cuotas',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='cuotas',
            name='fechas_de_pagos',
        ),
        migrations.RemoveField(
            model_name='cuotas',
            name='min_cuota',
        ),
        migrations.RemoveField(
            model_name='cuotas',
            name='porcentaje_inicial',
        ),
        migrations.CreateModel(
            name='FechasCuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('cuota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.cuotas')),
            ],
        ),
    ]
