# Generated by Django 5.0.4 on 2024-05-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cuotas_fecha_pago_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FechasCuotas',
        ),
    ]
