# Generated by Django 5.0.4 on 2024-05-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_delete_fechascuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotas',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='fechas_de_pagos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='min_cuota',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='porcentaje_inicial',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=5),
        ),
    ]
